'use client'

import { useState } from 'react'
import { Send, Paperclip, Mic } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import ChatMessage from '@/components/chat-message'

interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  citations?: number[]
  timestamp: Date
}

export default function ChatPanel() {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [sourceCount] = useState(0)

  const handleSend = () => {
    if (!input.trim()) return

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, userMessage])
    setInput('')
    setIsLoading(true)

    // Simulate assistant response
    setTimeout(() => {
      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: 'This is a sample response. In a real application, this would be generated by an AI model analyzing your sources.',
        citations: [1],
        timestamp: new Date(),
      }
      setMessages((prev) => [...prev, assistantMessage])
      setIsLoading(false)
    }, 800)
  }

  return (
    <div className="flex flex-1 flex-col border-r border-border bg-muted/50">
      {/* Header */}
      <div className="border-b border-border px-6 py-3 bg-card">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-semibold text-foreground">Discussion</h2>
          <div className="flex items-center gap-2">
            <button className="text-muted-foreground hover:text-foreground p-1 rounded hover:bg-muted">
              <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 4a1 1 0 011-1h5a1 1 0 011 1v2H3V4zm0 2v5h8V6H3zm0 7v5h8v-5H3zm10-7h5a1 1 0 011 1v2h-6V4zm0 2v5h6V6h-6zm0 7v5h6v-5h-6z" /></svg>
            </button>
            <button className="text-muted-foreground hover:text-foreground p-1 rounded hover:bg-muted">
              <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" /></svg>
            </button>
          </div>
        </div>
      </div>

      {/* Messages Container */}
      <div className="flex-1 overflow-y-auto">
        {messages.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full gap-6 px-6 py-12">
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
              <svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
              </svg>
            </div>
            <div className="text-center space-y-2">
              <h3 className="text-lg font-medium text-foreground">Add a source to begin</h3>
              <p className="text-sm text-muted-foreground max-w-sm">Upload documents, paste links, or search the web to get started with your research</p>
            </div>
            <Button className="mt-2 bg-background border border-border hover:bg-muted text-foreground">
              Import a source
            </Button>
          </div>
        ) : (
          <div className="space-y-6 p-6">
            {messages.map((message, index) => (
              <ChatMessage
                key={message.id}
                message={message}
                isLast={index === messages.length - 1 && isLoading}
              />
            ))}
            {isLoading && (
              <div className="flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
                  <div className="h-2 w-2 rounded-full bg-primary animate-pulse" />
                </div>
                <p className="text-sm text-muted-foreground">Thinking...</p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className="border-t border-border bg-card p-6">
        <div className="space-y-3">
          <div className="flex gap-2">
            <Button
              variant="ghost"
              size="icon"
              className="flex-shrink-0 text-muted-foreground hover:text-foreground"
            >
              <Paperclip className="h-5 w-5" />
            </Button>
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && e.ctrlKey) {
                  handleSend()
                }
              }}
              placeholder="Ask me anything about your sources..."
              className="min-h-12 resize-none border-input bg-input text-foreground placeholder:text-muted-foreground"
              rows={1}
            />
            <Button
              onClick={handleSend}
              disabled={!input.trim() || isLoading}
              className="flex-shrink-0 bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
              size="icon"
            >
              <Send className="h-5 w-5" />
            </Button>
          </div>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Mic className="h-4 w-4" />
            <span>Cmd+Enter to send • Attach files or paste links</span>
          </div>
        </div>
      </div>
    </div>
  )
}
